---

language: python

python:
  - "3.6"
  - "pypy3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install pandoc
  - pip install pypandoc

install:
  - pip install .

script:
  - python3 tests.py
